spring:
  cloud:
    vault:
      kv:
        enabled: true
        backend: kv
        default-context: aws-demo
        application-name: aws-demo
      aws:
        enabled: true
        role: s3
        backend: aws
        access-key-property: aws.accessKeyId
        secret-key-property: aws.secretKey
      authentication: TOKEN
      token: ${VAULT_TOKEN}
      uri: ${VAULT_ADDR}

spring.config.import: vault://
