spring:
  cloud:
    vault:
      kv:
        enabled: true
        backend: kv
        default-context: aws-demo
        application-name: aws-demo
      aws:
        enabled: true
        role: s3-role
        backend: aws
        credential-type: assumed_role
        access-key-property: aws.accessKeyId
        secret-key-property: aws.secretAccessKey
        session-token-key-property: aws.sessionToken
      authentication: TOKEN
      token: ${VAULT_TOKEN}
      uri: ${VAULT_ADDR}

spring.config.import: vault://
